# Generated by Django 5.2.4 on 2025-07-18 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='fecha_creacion',
            new_name='creado',
        ),
    ]
